'use server';

/**
 * @fileOverview Comprehensive career analysis flow.
 *
 * - comprehensiveAnalysis - A function that performs a complete analysis of a resume and job description.
 * - ComprehensiveAnalysisInput - The input type for the comprehensiveAnalysis function.
 * - ComprehensiveAnalysisOutput - The return type for the comprehensiveAnalysis function.
 */

import { ai } from '@/ai/genkit';
import { z } from 'genkit';

const JobSchema = z.object({
  title: z.string().describe('The job title.'),
  company: z.string().describe('The company name.'),
  location: z.string().describe('The job location.'),
  url: z.string().url().describe('A URL to the job posting. It should be a real and valid URL from a known job board like LinkedIn, Indeed, etc.'),
});

const ComprehensiveAnalysisInputSchema = z.object({
  resumeDataUri: z
    .string()
    .describe(
      "The resume file, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
  jobDescription: z.string().describe('The job description to analyze against.'),
});
export type ComprehensiveAnalysisInput = z.infer<typeof ComprehensiveAnalysisInputSchema>;

const ComprehensiveAnalysisOutputSchema = z.object({
  resumeInfo: z.object({
    skills: z.array(z.string()).describe('A list of skills extracted from the resume.'),
    experience: z.string().describe("A summary of the candidate's work experience."),
    education: z.string().describe("A summary of the candidate's education."),
    contactInformation: z.string().describe("A summary of the candidate's contact information."),
  }),
  jobInfo: z.object({
    requiredSkills: z.array(z.string()).describe('A list of required skills for the job.'),
    requiredExperience: z.string().describe('A description of the required experience for the job.'),
  }),
  feedback: z.object({
    feedback: z.string().describe('Feedback generated by GenAI to improve the resume for this specific role.'),
  }),
  jobRecommendations: z.array(JobSchema).describe('A list of at least 5 relevant job postings based on the candidate profile.'),
});
export type ComprehensiveAnalysisOutput = z.infer<typeof ComprehensiveAnalysisOutputSchema>;

export async function comprehensiveAnalysis(
  input: ComprehensiveAnalysisInput
): Promise<ComprehensiveAnalysisOutput> {
  return comprehensiveAnalysisFlow(input);
}

const prompt = ai.definePrompt({
  name: 'comprehensiveAnalysisPrompt',
  input: { schema: ComprehensiveAnalysisInputSchema },
  output: { schema: ComprehensiveAnalysisOutputSchema },
  prompt: `You are a Principal Career Consultant and Talent Acquisition Expert. 
  
  Your task is to perform a deep analysis of the provided Resume and Job Description.
  
  ### Inputs
  - **Resume (PDF)**: {{media url=resumeDataUri}}
  - **Job Description**: {{{jobDescription}}}
  
  ### Instructions
  1. **Candidate Profile Extraction**: Carefully parse the resume to extract technical and soft skills, work history summary, education details, and contact info.
  2. **Job Requirement Extraction**: Analyze the provided job description to identify essential skills and the expected level of experience.
  3. **Strategic Feedback**: Compare the candidate's profile against the job requirements. Provide constructive, actionable coaching on how they should optimize their resume to better align with this specific role. Be professional and high-impact.
  4. **Opportunity Matching**: Based on the candidate's skill set, find 5 real-world, relevant job opportunities. Ensure the URLs are direct and functional links to major job boards (LinkedIn, Indeed, etc.).
  
  Return the results as a strictly structured JSON object according to the output schema.`,
});

const comprehensiveAnalysisFlow = ai.defineFlow(
  {
    name: 'comprehensiveAnalysisFlow',
    inputSchema: ComprehensiveAnalysisInputSchema,
    outputSchema: ComprehensiveAnalysisOutputSchema,
  },
  async (input) => {
    const { output } = await prompt(input);
    if (!output) throw new Error('Failed to generate comprehensive analysis output.');
    return output;
  }
);
