'use server';

/**
 * @fileOverview This file defines a Genkit flow for generating feedback on a resume using GenAI.
 *
 * It includes the `generateResumeFeedback` function, which takes resume text as input and returns feedback.
 * The file also defines the input and output schemas for the flow.
 * @file
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

// Define the input schema
const GenerateResumeFeedbackInputSchema = z.object({
  resumeText: z.string().describe('The text content of the resume to provide feedback on.'),
});
export type GenerateResumeFeedbackInput = z.infer<typeof GenerateResumeFeedbackInputSchema>;

// Define the output schema
const GenerateResumeFeedbackOutputSchema = z.object({
  feedback: z.string().describe('Feedback generated by GenAI to improve the resume.'),
});
export type GenerateResumeFeedbackOutput = z.infer<typeof GenerateResumeFeedbackOutputSchema>;

// Define the Genkit flow
const generateResumeFeedbackFlow = ai.defineFlow(
  {
    name: 'generateResumeFeedbackFlow',
    inputSchema: GenerateResumeFeedbackInputSchema,
    outputSchema: GenerateResumeFeedbackOutputSchema,
  },
  async input => {
    const {output} = await generateResumeFeedbackPrompt(input);
    return output!;
  }
);

// Define the prompt
const generateResumeFeedbackPrompt = ai.definePrompt({
  name: 'generateResumeFeedbackPrompt',
  input: {schema: GenerateResumeFeedbackInputSchema},
  output: {schema: GenerateResumeFeedbackOutputSchema},
  prompt: `You are an expert career coach providing feedback on resumes.

  Provide constructive feedback to improve the resume. Be specific and actionable.

  Resume Text: {{{resumeText}}}`,
});

/**
 * Generates feedback on a resume using GenAI.
 * @param input The input containing the resume text.
 * @returns The output containing the generated feedback.
 */
export async function generateResumeFeedback(input: GenerateResumeFeedbackInput): Promise<GenerateResumeFeedbackOutput> {
  return generateResumeFeedbackFlow(input);
}
